import { defineConfig } from 'astro/config';
import preact from '@astrojs/preact';
import sitemap from '@astrojs/sitemap';
import tailwindcss from '@tailwindcss/vite';

import netlify from '@astrojs/netlify';

// https://astro.build/config
export default defineConfig({
  output: 'static',
  site: process.env.NODE_ENV === 'development'
    ? 'http://localhost:1234'
    : 'https://puffprovisions.com',
  integrations: [preact(), sitemap({
          filter: (page) => page !== 'https://puffprovisions.com/march-and-ash-mission-valley',
	})],

  // Redirects moved from _redirects file
  redirects: {
    // Newsletter redirects
    '/puffprovisionsweekly/issue-316': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-315': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-314': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-313': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-312': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-311': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-310': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-309': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-308': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-307': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-306': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-305': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-304': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-303': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-302': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-301': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-300': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-299': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-298': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-297': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-296': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-295': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-294': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-293': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-292': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-291': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-290': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-289': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-288': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-287': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-286': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-285': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-284': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-283': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-282': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-281': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-280': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-279': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-278': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-277': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-276': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-275': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-274': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-273': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-272': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-271': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-270': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-269': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-268': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-267': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-266': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-265': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-264': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-263': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-262': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-261': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-260': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-259': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-258': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-257': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-256': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-255': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-254': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-253': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-252': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-251': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-250': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-249': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-248': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-247': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-246': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-245': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-244': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-243': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-242': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-241': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-240': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-239': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-238': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-237': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-236': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-235': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-234': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-233': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-232': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-231': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-230': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-229': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-228': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-227': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-226': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-225': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-224': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-223': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-222': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-221': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-220': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-219': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-218': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-217': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-216': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-215': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-214': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-213': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-212': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-211': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-210': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-209': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-208': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-207': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-206': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-205': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-204': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-203': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-202': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-201': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-200': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-199': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-198': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-197': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-196': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-195': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-194': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-193': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-192': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-191': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-190': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-189': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-188': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-187': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-186': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-185': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-184': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-183': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-182': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-181': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-180': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-179': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-178': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-177': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-176': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-175': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-174': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-173': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-172': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-171': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-170': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-169': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-168': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-167': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-166': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-165': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-164': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-163': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-162': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-161': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-160': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-159': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-158': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-157': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-156': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-155': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-154': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-153': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-152': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-151': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-150': { destination: '/links', status: 301 },
    '/puffprovisionsweekly/issue-149': { destination: '/links', status: 301 },

    // Podcast redirects
    '/the-rorschach-test': { destination: '/the-rorschach-test-lost-tapes-edition', status: 301 },
    '/the-double-standard': { destination: '/the-double-standard-lost-tapes-edition', status: 301 },
    '/relics': { destination: '/relics-lost-tapes-edition', status: 301 },
    '/1-05-billion-jackpot': { destination: '/105-billion-jackpot', status: 301 },
    '/deconstructing-cobra-kai-high': { destination: '/deconstructing-cobra-kaihigh', status: 301 },
    '/how-to-create-a-cbd-cannabis-study-w-ansel': { destination: '/how-to-create-a-cbdcannabis-study-w-ansel', status: 301 },
    '/waiting-for-mike-again': { destination: '/waiting-for-mikeagain', status: 301 },
    '/seriously-what-dont-we-talk-about-on-this-episode': { destination: '/seriouslywhat-dont-we-talk-about-on-this-episode', status: 301 },
    '/weedmaps-museum-of-weed-part-1': { destination: '/weedmaps-museum-of-weed---part-1', status: 301 },
    '/cannabis-and-our-parenting-rules-tactics': { destination: '/cannabis-and-our-parenting-rulestactics', status: 301 },

    // Shop redirects
    '/shop/the-dart-x-puff-provisions': { destination: '/links', status: 301 },
    '/shop': { destination: '/links', status: 301 },
    '/cart': { destination: '/links', status: 301 },
    '/checkout': { destination: '/links', status: 301 },
    '/my-account': { destination: '/links', status: 301 },

    // Services redirects
    '/become-a-podcast-guest': { destination: '/contact', status: 301 },
    '/puff-provisions-weekly': { destination: '/contact', status: 301 },

    // Articles redirects
    '/articles': { destination: '/links', status: 301 },
    '/puff-provisions-unboxing-the-cannabis-manifesto-littofficial-stash-box': { destination: '/links', status: 301 },
    '/mastering-the-art-of-curing-how-an-automated-system-can-elevate-your-cultivation-game': { destination: '/links', status: 301 },
    '/the-ultimate-guide-to-cannabis-extraction-unlocking-the-power-of-terpenes': { destination: '/links', status: 301 },
    '/optimizing-your-dry-room-containment-control-and-cleanliness': { destination: '/links', status: 301 },
    '/mastering-plant-health-identifying-and-managing-stressors-for-a-thriving-grow': { destination: '/links', status: 301 },
    '/optimizing-npk-ratios-for-healthier-cannabis-growth': { destination: '/links', status: 301 },
    '/unlocking-the-power-of-terpenes-how-earth-fuel-fruit-and-floral-profiles-enhance-your-cannabis-experience': { destination: '/links', status: 301 },
    '/cultivating-stinging-nettle-plants-a-comprehensive-guide': { destination: '/links', status: 301 },
    '/the-role-of-light-in-modern-cannabis-cultivation-unlocking-growth-potential': { destination: '/links', status: 301 },
    '/the-ultimate-guide-to-water-sources-for-cultivation-agricultural-well-water-vs-municipal-water': { destination: '/links', status: 301 },
    '/mastering-nutrient-management-in-plant-growth-a-complete-guide': { destination: '/links', status: 301 },
    '/introduction-to-clones-a-beginners-guide-to-plant-cloning-and-cannabis-cultivation': { destination: '/links', status: 301 },
    '/cannabis-research-trends-and-challenges-in-2024': { destination: '/links', status: 301 },
    '/breaking-down-barriers-social-equity-in-the-cannabis-industry': { destination: '/links', status: 301 },
    '/vendor-evaluation-criteria-for-cannabis-businesses-a-comprehensive-guide': { destination: '/links', status: 301 },
    '/the-endocannabinoid-system-natures-balancing-act': { destination: '/links', status: 301 },
    '/understanding-photoperiod-and-its-role-in-the-flowering-cycle': { destination: '/links', status: 301 },
    '/a-brief-history-of-medicinal-cannabis-from-discovery-to-modern-advocacy': { destination: '/links', status: 301 },
    '/lowells': { destination: '/links', status: 301 },
    '/heavy-hitters-vape': { destination: '/links', status: 301 },
    '/series-iii-cancelled': { destination: '/links', status: 301 },
    '/puff-provisions-grow-series-iii': { destination: '/links', status: 301 },
    '/island-flower': { destination: '/links', status: 301 },
    '/84-more-grams': { destination: '/links', status: 301 },
    '/indoor-grow-shopping-list': { destination: '/links', status: 301 },
    '/continuing-education-through-cannabis': { destination: '/links', status: 301 },
    '/the-potential-risks-of-thc': { destination: '/links', status: 301 },
    '/benefits-of-cbd': { destination: '/links', status: 301 },
    '/cannabis-understanding-the-pros-and-cons-of-this-controversial-plant': { destination: '/links', status: 301 },
    '/the-grow-series-1-retrospective': { destination: '/links', status: 301 },
    '/puff-provisions-grow-series-ii': { destination: '/links', status: 301 },
    '/cannabis-stocks': { destination: '/links', status: 301 },
    '/legal-vs-illegal-dispensaries': { destination: '/links', status: 301 },
    '/the-puff-provisions-grow': { destination: '/links', status: 301 },
    '/liiil-stiiizy': { destination: '/links', status: 301 },
    '/tyson-ranch': { destination: '/links', status: 301 },
    '/litt-stash-box': { destination: '/links', status: 301 },
    '/nectar-cbd-drink': { destination: '/links', status: 301 },
    '/original-ks-cbd-sleep': { destination: '/links', status: 301 },
    '/original-k-cbd-fit': { destination: '/links', status: 301 },
    '/looking-back-on-the-2019-american-cbd-expo': { destination: '/links', status: 301 },
    '/kingpen-trainwreck': { destination: '/links', status: 301 },
    '/whats-your-relationship-to-cannabis': { destination: '/links', status: 301 },
    '/countdown-to-04-20-19': { destination: '/links', status: 301 },
    '/full-spectrum-cbd-oil': { destination: '/links', status: 301 },
    '/royal-blunts-xxl-cigar-wrap': { destination: '/links', status: 301 },
    '/good-flower-sativa': { destination: '/links', status: 301 },

    // Contact redirects
    '/contact-us': { destination: '/contact', status: 301 },
    '/profile/puffprovisionsdarrell': { destination: '/about', status: 301 },
    '/profile/puffprovisionsmike': { destination: '/about', status: 301 },
    '/team': { destination: '/about', status: 301 },
    '/profile/puffprovisionsmark': { destination: '/about', status: 301 },
    '/hello-and-welcome': { destination: '/about', status: 301 },
    '/terms-of-service': { destination: '/about', status: 301 },
    '/privacy-policy': { destination: '/about', status: 301 },
    '/submit-a-link': { destination: '/contact', status: 301 },
    '/mission-statement': { destination: '/about', status: 301 },
    '/affiliate-disclosure': { destination: '/links', status: 301 },
    '/reborn-crew-neck-giveaway': { destination: '/links', status: 301 },

    // Fallback (for all other routes)
    '/*': { destination: 'https://puffprovisions.com', status: 301 }
  },

  vite: {
    plugins: [tailwindcss()]
  },

  adapter: netlify()
});
